---

# install dependencies for monitoring
- name: Install monitoring packages
  apt:
    name:
      - promtail
      - prometheus-node-exporter
    state: present

# create monitoring directories
- name: Ensure monitoring directory exists
  file:
  path: /home/{{ ansible_user }}/{{ my_project }}/monitoring/
    state: directory

- name: Ensure promtail directory exists
  file:
    path: /home/{{ ansible_user }}/{{ my_project }}/monitoring/promtail/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

# - name: Ensure positions.yml exists
#   file:
#     path: /home/{{ ansible_user }}/{{ my_project }}/monitoring/promtail/positions.yaml
#     state: touch

- name: Ensure node_exporter directory exists
  file:
    path: /home/{{ ansible_user }}/{{ my_project }}/monitoring/node_exporter/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'