---

- name: Install Docker
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes
  
- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add current user to docker group
  user:
    name: "{{ web01_user }}"
    groups: docker
    append: true


# Copy docker compose file
- name: Copy docker compose file
  copy:
    src: "{{ dcompose_path }}"
    dest: /home/{{ ansible_user }}/{{ my_project }}/docker-compose.yml
    owner: "{{ web01_user }}"
    group: "{{ web01_user }}"