services:
  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    profiles:
    - monitoring
    volumes:
      - ./promtail/promtail_config.yml:/etc/promtail/promtail.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-positions:/monitoring/promtail/positions
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    command:
    - -config.file=/etc/promtail/promtail.yml -config.expand-env=true
    - -config.expand-env=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  node-exporter:
    restart: unless-stopped
    image: prom/node-exporter:latest
    profiles:
    - monitoring
    network_mode: host
    pid: host
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    - /run/udev/data:/run/udev/data:ro
    command:
    - '--path.procfs=/host/proc'
    - '--path.sysfs=/host/sys'
    - '--path.rootfs=/rootfs'
    - '--log.level=warn'

  prometheus-agent:
    image: prom/prometheus:latest
    restart: unless-stopped
    profiles:
    - monitoring
    env_file:
      - .env
    volumes:
      - ./prometheus.template.yml:/etc/prometheus/prometheus.template.yml
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=warn'

  backend:
    image: ${DOCKER_NAME}/blog-backend:latest
    restart: unless-stopped
    profiles:
    - app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_net
    

networks:
  app_net:
    driver: bridge

volumes:
  promtail-positions:
