services:
  promtail:
    image: grafana/promtail:latest
    profiles:
    - monitoring
    volumes:
      - ./promtail/promtail_config.yml:/etc/promtail/promtail.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-positions:/monitoring/promtail/positions
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    command:
    - -config.file=/etc/promtail/promtail.yml
    - -config.expand-env=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  node-exporter:
    image: prom/node-exporter:latest
    profiles:
    - monitoring
    networks:
      - monitoring_net
    pid: host
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    - /run/udev/data:/run/udev/data:ro
    command:
    - '--path.procfs=/host/proc'
    - '--path.sysfs=/host/sys'
    - '--path.rootfs=/rootfs'
    - '--log.level=warn'

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor
  #   profiles:
  #   - monitoring
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   devices:
  #   - /dev/kmsg:/dev/kmsg
  #   command:
  #   - '--v=0'
  #   networks:
  #     - monitoring_net

  prometheus-agent:
    image: prom/prometheus:latest
    profiles:
    - monitoring
    env_file:
      - .env
    networks:
      - monitoring_net
    volumes:
      - ./prometheus/prometheus.template.yml:/etc/prometheus/prometheus.template.yml
      - ./prometheus/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--log.level=warn'
      - '--agent'

  backend:
    image: ${DOCKER_NAME}/blog-backend:latest
    restart: unless-stopped
    profiles:
    - app
    ports:
      - "8000:8000"
    env_file:
      - .env
    

networks:
  monitoring_net:
    driver: bridge

volumes:
  promtail-positions:
