---

# Common dependencies

- name: Install common packages
  apt:
    name:
      - ca-certificates
      - curl
      - wget
      - git
      - vim
      - htop
      - unzip
      - rsync
      - gnupg
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist

# create project directory

- name: Ensure project directory exists
  file:
    path: /home/{{ web01_user }}/{{ my_project }}
    state: directory
    owner: "{{ web01_user }}"
    group: "{{ web01_user }}"
    mode: '0755'

# .env

- name: Write .env from secret
  copy:
    content: "{{ lookup('file', env_content_file) }}"
    dest: /home/{{ web01_user }}/{{ my_project }}/.env
    owner: "{{ web01_user }}"
    group: "{{ web01_user }}"
    mode: '600'
# Firewall

- name: Ensure ufw is installed
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow app port 8000
  ufw:
    rule: allow
    port: "8000"
    proto: tcp

- name: Enable firewall
  ufw:
    state: enabled


