---

# Copy monitoring configuration files and create the destination directory if it doesn't exist
- name: Copy monitoring configuration files recursively to the project directory
  copy:
    src: "{{ monitoring_dir }}/"
    dest: /home/{{ web01_user }}/{{ my_project }}/monitoring/
    recursive: yes