---

- name: Ensure destination monitoring directory exists
  ansible.legacy.file:
    path: /home/{{ web01_user }}/{{ my_project }}/monitoring/
    state: directory

- name: copy monitoring configuration files
  ansible.legacy.synchronize:
    src: "{{ monitoring_dir }}/"
    dest: /home/{{ web01_user }}/{{ my_project }}/monitoring/
    mode: push
