name: Project Pipeline
on:
  push:
    branches:
      - main
      - test

jobs:
  setup-key:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Create directory and save SSH key
        run: |
          mkdir -p ~/.ssh/private_key_dir
          echo "${{ secrets.PRIVATE_KEY_WEB01 }}" > ~/.ssh/private_key_dir/web01_key
          chmod 700 ~/.ssh/private_key_dir
          chmod 600 ~/.ssh/private_key_dir/web01_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/private_key_dir/web01_key

  ansible-run:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: setup-key
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ansible
        uses: ansible/ansible-galaxy-action@v2

      - name: Run Ansible Playbook
        env:
          PUBLIC_IP_WEB01: ${{ vars.PUBLIC_IP_WEB01 }}
          ENV_CONTENT: ${{ secrets.ENV_CONTENT }}
          WEB01_USER: ${{ vars.WEB01_USER }}
        run: |
          ansible-playbook -i inventory.ini playbook.yml \
          -e "public_ip_web01=$PUBLIC_IP_WEB01" \
          -e "env_content=$ENV_CONTENT" \
          -e "web01_user=$WEB01_USER"

  
  test-job:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt
      - run: pip install ruff pytest

      - run: ruff check .
      - run: pytest
