name: Infrastructure Pipeline
on:
  push:
    branches: [main, test]
    paths:
      - 'infra/**'
      
jobs:
  ansible-run:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: "infra"

      - name: Set up SSH Agent and load key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_WEB01 }}

      - name: Add server to known_hosts (Using run command)
        run: |
          # 1. Ensure the directory exists
          mkdir -p ~/.ssh
          # 2. Scan the host key using your variable and append it to known_hosts
          ssh-keyscan -H ${{ vars.PUBLIC_IP_WEB01 }} >> ~/.ssh/known_hosts

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        env:
          PUBLIC_IP_WEB01: ${{ vars.PUBLIC_IP_WEB01 }}
          ENV_CONTENT: ${{ secrets.ENV_CONTENT }}
          WEB01_USER: ${{ vars.WEB01_USER }}
        working-directory: infra/ansible
        run: |
          ansible-playbook -i inventory.yml playbook.yml \
            -e "env_content=$ENV_CONTENT" \
            -e "web01_user=$WEB01_USER"
  
  # docker-compose-run:
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest